Controllers/AuthorController.cs
using Pidev_front.Models;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
namespace Pidev_front.Controllers
{
    public class AuthorController : Controller
    {
        HttpClient httpClient;

        public AuthorController()
        {
            httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri("http://localhost:8080/");
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }
        // GET: Author
        public ActionResult Index()
        {
            var response = httpClient.GetAsync("get_allAuthors").Result;

            if (response.IsSuccessStatusCode)
            {
                var authors = response.Content.ReadAsAsync<IList<Author>>().Result;
                return View(authors);
            }
            else
            {
                return View(new List<Author>());
            }
        }

        // GET: Author/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }


        // GET: Author/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Author/Create
        [HttpPost]
        public ActionResult Create(Author author)
        {
            try
            {
                author.Id = null;
                var response = httpClient.PostAsJsonAsync("add_Author", author).ContinueWith(task =>

             {
                 if (task.Result.IsSuccessStatusCode)
                 {
                     var result = task.Result.Content.ReadAsStringAsync();
                 }
                 else
                 {
                     task.Result.EnsureSuccessStatusCode();
                 }

             });
          
              
            }
            catch
            {
                return View();
            }

            return RedirectToAction("Index");
        }

        // GET: Author/Edit/5
        public ActionResult Edit(int id)
        {
            var response = httpClient.GetAsync("author/" + id.ToString()).Result;
            if (response.IsSuccessStatusCode)
            {
                var author = response.Content.ReadAsAsync<Author>().Result;
                return View(author);
            }
            else
            {
                return View(new Author());
            }
        }

        // POST: Author/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Author author)
        {
            try
            {
                var response = httpClient.PutAsJsonAsync("update-Author/" + id.ToString(), author).ContinueWith(task =>
                {
                    if (task.Result.IsSuccessStatusCode)
                    {
                        var result = task.Result.Content.ReadAsStringAsync();
                    }
                    else
                    {
                        task.Result.EnsureSuccessStatusCode();
                    }
                });
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Author/Delete/5
        public ActionResult Delete(int id)
        {
            var response = httpClient.GetAsync("author/" + id.ToString()).Result;
            if (response.IsSuccessStatusCode)
            {
                var author = response.Content.ReadAsAsync<Author>().Result;
                return View(author);
            }
            else
            {
                return View(new Author());
            }
        }

        // POST: Author/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {

                var response = httpClient.DeleteAsync("remove-Author/" + id.ToString()).ContinueWith(task =>
                {
                    if (task.Result.IsSuccessStatusCode)
                    {
                        var result = task.Result.Content.ReadAsStringAsync();
                    }
                    else
                    {
                        task.Result.EnsureSuccessStatusCode();
                    }
                });
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

Controllers/BookController.cs
using Pidev_front.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace Pidev_front.Controllers
{
    public class BookController : Controller
    {

        HttpClient httpClient;
        List<SelectListItem> list = new List<SelectListItem>();

    public BookController()
        {
            httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri("http://localhost:8080/");
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        // GET: Book
        public ActionResult Index()
        {

            var response = httpClient.GetAsync("get-all-books").Result;
        
            if (response.IsSuccessStatusCode)
            {
                var books = response.Content.ReadAsAsync<IList<Book>>().Result;
                return View(books);
            }
            else
            {
                return View(new List<Book>());
            }   
        }

        // GET: Book/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Book/Create
        public ActionResult Create()
        {

            List<SelectListItem> authorOptionList = new List<SelectListItem>();
            List<SelectListItem> publishingHousesOptionList = new List<SelectListItem>();
            List<SelectListItem> categoriesOptionList = new List<SelectListItem>();






            var response = httpClient.GetAsync("get_allAuthors").Result;

            if (response.IsSuccessStatusCode)
            {
                var authors = response.Content.ReadAsAsync<IList<Author>>().Result;

                foreach (var element in authors)
                {
                    authorOptionList.Add(new SelectListItem
                    {
                        Text = element.FirstName + element.LastName,
                        Value = element.Id.ToString()
                    });
                }

            }

            var response2 = httpClient.GetAsync("get-all-PublishingHouses").Result;

            if (response2.IsSuccessStatusCode)
            {
                var publishingHouses = response2.Content.ReadAsAsync<IList<PublishingHouse>>().Result;

                foreach (var element in publishingHouses)
                {
                    publishingHousesOptionList.Add(new SelectListItem
                    {
                        Text = element.Name,
                        Value = element.Id.ToString()
                    });
                }
            }

       

          

            var response3 = httpClient.GetAsync("get-all-categories").Result;

            if (response3.IsSuccessStatusCode)
            {
                var categories = response3.Content.ReadAsAsync<IList<Category>>().Result;
                foreach (var element in categories)
                {
                    categoriesOptionList.Add(new SelectListItem
                    {
                        Text = element.Title,
                        Value = element.Id.ToString()
                    });
                }
            }
           

 




            ViewBag.authorOptionList = authorOptionList;
            ViewBag.publishingHousesOptionList = publishingHousesOptionList;
            ViewBag.categoriesOptionList = categoriesOptionList;

            /*  var response = httpClient.GetAsync("get-all-books").Result;

              if (response.IsSuccessStatusCode)
              {
                  var books = response.Content.ReadAsAsync<IList<Book>>().Result;
                  var author = new Author() ;
                //  author.books = books;
                  return View(books);
              }
              else
              {
                  return View(new List<Book>());
              }
            */

            return View();
          
        }

        // POST: Book/Create
        [HttpPost]
        public ActionResult Create(Book book)
        {
            
                // TODO: Add insert logic here

                try
                {
                book.categorieIds.Add(book.categoryId); 


                    var response = httpClient.PostAsJsonAsync("add_book", book).ContinueWith(task =>

                    {
                        if (task.Result.IsSuccessStatusCode)
                        {
                            var result = task.Result.Content.ReadAsStringAsync();
                        }
                        else
                        {
                            task.Result.EnsureSuccessStatusCode();
                        }

                    });
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }

           
           
        }

        // GET: Book/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Book/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Book/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Book/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
 
        
    }

   
}

Controllers/OrderController.cs
using Pidev_front.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace Pidev_front.Controllers
{
    public class OrderController : Controller
    {
        HttpClient httpClient;

        public OrderController()
        {
            httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri("http://localhost:8080/order/");
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        // GET: Order
        public ActionResult Index()
        {
            var response = httpClient.GetAsync("all").Result;
            if (response.IsSuccessStatusCode)
            {
                var orders = response.Content.ReadAsAsync<IList<Order>>().Result;
                return View(orders);
            }
            else
            {
                return View(new List<Order>());
            }
        }

        public ActionResult New()
        {
            var response = httpClient.GetAsync("new").Result;
            if (response.IsSuccessStatusCode)
            {
                var orders = response.Content.ReadAsAsync<IList<Order>>().Result;
                return View(orders);
            }
            else
            {
                return View(new List<Order>());
            }
        }


        public ActionResult Ongoing()
        {
            var response = httpClient.GetAsync("ongoing").Result;
            if (response.IsSuccessStatusCode)
            {
                var orders = response.Content.ReadAsAsync<IList<Order>>().Result;
                return View(orders);
            }
            else
            {
                return View(new List<Order>());
            }
        }


        public ActionResult Delivered()
        {
            var response = httpClient.GetAsync("delivered").Result;
            if (response.IsSuccessStatusCode)
            {
                var orders = response.Content.ReadAsAsync<IList<Order>>().Result;
                return View(orders);
            }
            else
            {
                return View(new List<Order>());
            }
        }


        public ActionResult Stats()
        {
            var response = httpClient.GetAsync("stats").Result;
            if (response.IsSuccessStatusCode)
            {
                var orderStats = response.Content.ReadAsAsync<OrderStats>().Result;
                return View(orderStats);
            }
            else
            {
                return View();
            }

        }

        [HttpPost]
        public ActionResult UpdateStatus(Order order)
        {

            string id = (string)Request.Form["orderId"];
            string status = (string)Request.Form["selectedValue"];

            var response = httpClient.PutAsJsonAsync("update-status/"+id+"/"+status, order).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

Controllers/PromotionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Net.Http.Headers;
using Pidev_front.Models;

namespace Pidev_front.Controllers
{
    public class PromotionController : Controller
    {
        HttpClient httpClient;
        List<SelectListItem> list = new List<SelectListItem>();


        public PromotionController()
        {
            httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri("http://localhost:8080/");
            httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }


        public ActionResult Index()
        {
            var response = httpClient.GetAsync("get-all-Promotions").Result;

            if (response.IsSuccessStatusCode)
            {
                var promotions = response.Content.ReadAsAsync<IList<Promotion>>().Result;
                return View(promotions);
            }
            else
            {
                return View(new List<Promotion>());
            }
        }

        // GET: Promotion/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Promotion/Create
        public ActionResult Create()
        {
            List<SelectListItem> bookOptionList = new List<SelectListItem>();

            var response = httpClient.GetAsync("get-all-books").Result;

            if (response.IsSuccessStatusCode)
            {
                var books = response.Content.ReadAsAsync<IList<Book>>().Result;

                foreach (var element in books)
                {
                    bookOptionList.Add(new SelectListItem
                    {
                        Text = element.Title,
                        Value = element.Id.ToString()
                    });
                }

            }


            ViewBag.bookOptionList = bookOptionList;




            return View();
        }

        // POST: Promotion/Create
        [HttpPost]
        public ActionResult Create(Promotion promotion)
        {
            try
            {

                promotion.booksIds.Add(promotion.bookId);
                var response = httpClient.PostAsJsonAsync("add-Promotion", promotion).ContinueWith(task =>

                {


                    if (task.Result.IsSuccessStatusCode)
                    {
                        var result = task.Result.Content.ReadAsStringAsync();
                    }
                    else
                    {
                        task.Result.EnsureSuccessStatusCode();
                    }

                });
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Promotion/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Promotion/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Promotion/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Promotion/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

<style>
        .navbar {
            font-size: 14px;
            background-color: #282A35;
            color: #f1f1f1;
            width: 100%;
            padding: 0;
            letter-spacing: 1px;
            font-family: 'Source Sans Pro', sans-serif;
        }

        .container-fluid {
            padding-left: 315px !important;
        }

        /* ⚠️ Warning! ⚠️
       SOME CSS IS BEING REFERENCED IN THE SETTINGS
       BE SURE TO REFERENCE BOOSTRAP 3
       BE SURE TO REFERENCE HOVER.CSS
       CHECK CODEPEN SETTINGS > HTML & CSS TABS
    */

        .footer h4 {
            font-weight: 600;
            padding-bottom: 10px;
            color: #2D2D2D;
        }

        .footer a {
            text-decoration: none;
            color: #888888;
        }

            .footer a:hover {
                color: #EE4466;
            }

        .footer-rowtop {
            padding: 40px 20px;
            color: #888888;
        }

        .footer-rowbottom {
            padding: 30px 20px;
            background: #F3F3F3;
            color: #888888;
        }

        .footer-links {
            line-height: 24px;
        }

        .footer-social-icons {
            padding-right: 15px;
        }

        /* CSS for Form Field */
        /* ------------------------------- */

        input[type=text], select {
            width: 70%;
            padding: 8px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

/*        input[type=submit] {
            width: 28%;
            background-color: #888888;
            color: white;
            padding: 9px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }*/

            input[type=submit]:hover {
                background-color: #A1AEB7;
            }

        div .forrm {
            border-radius: 5px;
        }

        footer {
            position: fixed;
            bottom: 0;
            width: 100%;
        }

        /* ------------------------------- */



</style>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Bibliophile", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                <li>@Html.ActionLink("Book list", "Index", "Book")</li>
                <li>@Html.ActionLink("Promotion list", "Index", "Promotion")</li>
                <li>@Html.ActionLink("Categories list", "Index", "Category")</li>
                <li>@Html.ActionLink("Authors list", "Index", "Author")</li>
                <li>@Html.ActionLink("Publishing House List", "Index", "PublishingHouse")</li>
                <li>@Html.ActionLink("statistics", "Index", "Statistique")</li>
                <li>@Html.ActionLink("Coupon Managment", "Index", "Coupons")</li>
                <li>@Html.ActionLink("Order Managment", "Index", "Order")</li>
            </ul>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <footer class="container" style="width: 100%">
        <hr />
        @*<div class="row footer-rowtop  ">

            <div class="col-sm-2 footer-links">
                <h4>Solutions</h4>
                <a href="#">For Employers</a>
                <br />
                <a href="#">For Partners</a>
                <br />
                <a href="#">Pricing</a>
                <br />
            </div>

            <div class="col-sm-2 footer-links">
                <h4>Resources</h4>
                <a href="#">Library</a>
                <br />
                <a href="#">News</a>
                <br />
                <a href="#">Events</a>
                <br />
            </div>

            <div class="col-sm-2 footer-links">
                <h4>Company</h4>
                <a href="#">About</a>
                <br />
                <a href="#">Contact</a>
                <br />
                <a href="#">Careers</a>
                <br />
            </div>

            <div class="col-sm-2 footer-links">
                <h4>Support</h4>
                <a href="#">Privacy</a>
                <br />
                <a href="#">Security</a>
                <br />
                <a href="#">Help Center</a>
                <br />
            </div>

            <div class="col-sm-4 footer-links">
                <h4>Newsletter:</h4>
                Benefits, News, and Trends right to your inbox.
                <div class="forrm">
                    <form action="/action_page.php">
                        <input type="text" id="fname" name="firstname" placeholder="Enter Email">
                        <input type="submit" value="Sign Up" class="btn btn-success">
                    </form>
                </div>

            </div>
        </div>*@

        <div class="row footer-rowbottom">

            <div class="col-sm-4">
                <i class="fab fa-facebook-square fa-3x "></i>
                <i class="fab fa-linkedin fa-3x"></i>
                <i class="fab fa-twitter-square fa-3x"></i>
                <i class="fab fa-instagram fa-3x"></i>
            </div>

            <div class="col-sm-4">

            </div>
            <div class="col-sm-4">
                <br />© All Stars. 2021| <a href="#">Privacy Policy</a>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>